[package]
name = "pqdump"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
comfy-table = { version = "7", default-features = false }

arrow-array = "45"
arrow-cast = "45"
parquet = "45"

[profile.release]
lto = true
codegen-units = 1
