[package]
name = "pqdump"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
comfy-table = { version = "7", default-features = false }

arrow-array = "44"
arrow-cast = "44"
parquet = "44"

zstd = { version = "0.12", features = ["pkg-config"] }

[profile.release]
lto = true
codegen-units = 1
