[package]
name = "pqdump"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tabled = "0.13"
tryiterator = { git = "https://github.com/Pernosco/tryiterator.git" }

arrow-array = "44"
arrow-cast = "44"
arrow-schema = "44"
parquet = "44"

[profile.release]
lto = true
codegen-units = 1
